refactor: Add production deployment job with artifact download and staging deployment steps

diff --git a/.github/workflows/hugo.yml b/.github/workflows/hugo.yml
--- a/.github/workflows/hugo.yml
+++ b/.github/workflows/hugo.yml
@@ -113,3 +113,28 @@ jobs:
           external_repository: garrardkitchen/blog-staging
           publish_branch: main
           cname: blog-staging.garrardkitchen.com
+  deploy_production:
+    needs: deploy_staging
+    runs-on: ubuntu-latest
+    environment:
+      name: production
+      url: https://blog.garrardkitchen.com
+    steps:
+      - name: Download public directory artifact
+        uses: actions/download-artifact@v4.2.1
+        with:
+          name: public-artifact
+          path: ./public
+      - name: Debug Public Directory
+        run: |
+          echo "Contents of public directory:"
+          ls -al ./public || echo "Public directory not found!"
+      - name: Deploy to staging
+        id: staging
+        uses: peaceiris/actions-gh-pages@v4
+        with:
+          personal_token: ${{ secrets.PAT_SCOPE_REPO }}
+          publish_dir: ./public
+          external_repository: garrardkitchen/blog-prod
+          publish_branch: main
+          cname: blog.garrardkitchen.com
